# Generated by Django 3.0.7 on 2021-11-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='id',
            new_name='sno',
        ),
    ]
